 let users=[{"id":1,"name":"Hattie","car":"Honda","city":"Tayang"},
{"id":2,"name":"Pris","car":"Lotus","city":"Shimotoda"},
{"id":3,"name":"Malory","car":"Dodge","city":"Xintang"},
{"id":4,"name":"Brittne","car":"Mitsubishi","city":"Sosnovka"},
{"id":5,"name":"Osbourn","car":"GMC","city":"Kilinochchi"},
{"id":6,"name":"Thacher","car":"GMC","city":"Charleston"},
{"id":7,"name":"Tiffany","car":"Cadillac","city":"Tula"},
{"id":8,"name":"Jilli","car":"Lexus","city":"Jonquière"},
{"id":9,"name":"Bobina","car":"Chevrolet","city":"Aibura"},
{"id":10,"name":"Averell","car":"Lamborghini","city":"Dalsjöfors"},
{"id":11,"name":"Mahalia","car":"Chrysler","city":"Jäppilä"},
{"id":12,"name":"Mehetabel","car":"Mitsubishi","city":"Duque de Caxias"},
{"id":13,"name":"Anica","car":"MINI","city":"Glugu"},
{"id":14,"name":"Briny","car":"BMW","city":"Pyatovskiy"},
{"id":15,"name":"Somerset","car":"Daewoo","city":"Soavinandriana"},
{"id":16,"name":"Tabb","car":"Buick","city":"Mercier"},
{"id":17,"name":"Innis","car":"Mitsubishi","city":"Langchi"},
{"id":18,"name":"Boone","car":"Dodge","city":"Sendafa"},
{"id":19,"name":"Nelson","car":"Volkswagen","city":"Ylöjärvi"},
{"id":20,"name":"Kathye","car":"BMW","city":"Boston"},
{"id":21,"name":"Ive","car":"Audi","city":"Fuming"},
{"id":22,"name":"Jessamyn","car":"Plymouth","city":"Qinling Jieban"},
{"id":23,"name":"Eliot","car":"Acura","city":"Francisco Beltrão"},
{"id":24,"name":"Carley","car":"Hyundai","city":"Khao Yoi"},
{"id":25,"name":"Fidel","car":"Mazda","city":"Loyola"},
{"id":26,"name":"Korrie","car":"Ford","city":"Leipzig"},
{"id":27,"name":"Leland","car":"Ford","city":"Kalnibolotskaya"},
{"id":28,"name":"Elnar","car":"Ford","city":"Urpay"},
{"id":29,"name":"Dulci","car":"GMC","city":"Junín"},
{"id":30,"name":"Sibella","car":"Buick","city":"Heshang"},
{"id":31,"name":"Earle","car":"Lexus","city":"Sirāhā"},
{"id":32,"name":"Trudey","car":"Mercury","city":"Jurak Lao’"},
{"id":33,"name":"Caty","car":"Mazda","city":"Banjarejo"},
{"id":34,"name":"Janeta","car":"Audi","city":"Alcains"},
{"id":35,"name":"Luelle","car":"Buick","city":"Gananoque"},
{"id":36,"name":"Tony","car":"Mercedes-Benz","city":"Bishan"},
{"id":37,"name":"Bondie","car":"Audi","city":"Solnechnyy"},
{"id":38,"name":"Beck","car":"Hyundai","city":"Murree"},
{"id":39,"name":"Sibylle","car":"Cadillac","city":"Anka"},
{"id":40,"name":"Linnell","car":"BMW","city":"Cabiguan"},
{"id":41,"name":"Ripley","car":"Mazda","city":"Tríkala"},
{"id":42,"name":"Maddy","car":"Plymouth","city":"Chicago"},
{"id":43,"name":"Johnathon","car":"Mercury","city":"Saku"},
{"id":44,"name":"Harmonie","car":"Oldsmobile","city":"Alpūrai"},
{"id":45,"name":"Arturo","car":"BMW","city":"Chongru"},
{"id":46,"name":"Judd","car":"Jeep","city":"Wum"},
{"id":47,"name":"Dorothee","car":"Chevrolet","city":"Ondores"},
{"id":48,"name":"Binni","car":"Lincoln","city":"Reading"},
{"id":49,"name":"Roanna","car":"Chevrolet","city":"Nomhon"},
{"id":50,"name":"Jayson","car":"Suzuki","city":"Miandrivazo"},
{"id":51,"name":"Ignatius","car":"Volkswagen","city":"Białogard"},
{"id":52,"name":"Baxy","car":"Ford","city":"Bang Sai"},
{"id":53,"name":"Cherida","car":"Scion","city":"Xinshi"},
{"id":54,"name":"Win","car":"Peugeot","city":"Vila Real de Santo António"},
{"id":55,"name":"Karola","car":"Nissan","city":"Palencia"},
{"id":56,"name":"Charlean","car":"Oldsmobile","city":"Kertorejo"},
{"id":57,"name":"Paolina","car":"Chevrolet","city":"Sabana de Parra"},
{"id":58,"name":"Bernice","car":"Pontiac","city":"La Tigra"},
{"id":59,"name":"Raina","car":"Ford","city":"Prinza"},
{"id":60,"name":"Tymothy","car":"BMW","city":"Jiujie"},
{"id":61,"name":"Brnaby","car":"Toyota","city":"Banja Luka"},
{"id":62,"name":"Roseanna","car":"Mazda","city":"Roshal’"},
{"id":63,"name":"Jedidiah","car":"Infiniti","city":"Huicheng"},
{"id":64,"name":"Almeria","car":"Ford","city":"Hedong"},
{"id":65,"name":"Redd","car":"Chevrolet","city":"Tegallega"},
{"id":66,"name":"Billie","car":"Kia","city":"Vila Nova"},
{"id":67,"name":"Tommy","car":"Jaguar","city":"Ruzayevka"},
{"id":68,"name":"Linn","car":"Chevrolet","city":"Hafrsfjord"},
{"id":69,"name":"Suzanne","car":"Saab","city":"Burnaby"},
{"id":70,"name":"Effie","car":"Nissan","city":"Jasper Park Lodge"},
{"id":71,"name":"Klarrisa","car":"Volkswagen","city":"Shatalovo"},
{"id":72,"name":"Lizette","car":"Ford","city":"Buta Ranquil"},
{"id":73,"name":"Donal","car":"Dodge","city":"Zango"},
{"id":74,"name":"Antonia","car":"Porsche","city":"Magersari"},
{"id":75,"name":"Saleem","car":"Nissan","city":"Quintela"},
{"id":76,"name":"Caresse","car":"Chevrolet","city":"Buyuan"},
{"id":77,"name":"Livy","car":"Kia","city":"Boshkengash"},
{"id":78,"name":"Corly","car":"Toyota","city":"Owo"},
{"id":79,"name":"Roseanne","car":"Pontiac","city":"Brzeszcze"},
{"id":80,"name":"Bertine","car":"Aston Martin","city":"Kamaris"},
{"id":81,"name":"Faustina","car":"GMC","city":"Sidomulyo"},
{"id":82,"name":"Francklin","car":"Isuzu","city":"Yaogu"},
{"id":83,"name":"Jacynth","car":"Honda","city":"Cauayan"},
{"id":84,"name":"Deni","car":"Oldsmobile","city":"Tanjung Palas"},
{"id":85,"name":"Welbie","car":"Mercedes-Benz","city":"Calumpang"},
{"id":86,"name":"Ginnie","car":"Nissan","city":"Caimitillo"},
{"id":87,"name":"Sarina","car":"Oldsmobile","city":"Cornwall"},
{"id":88,"name":"Elias","car":"Morgan","city":"Darungan"},
{"id":89,"name":"Daphna","car":"Volvo","city":"Jdaidet el Matn"},
{"id":90,"name":"Honey","car":"GMC","city":"Polomolok"},
{"id":91,"name":"Ulises","car":"GMC","city":"Chinchiná"},
{"id":92,"name":"Brendon","car":"Buick","city":"Kuala Lumpur"},
{"id":93,"name":"Muffin","car":"Acura","city":"Tambillo"},
{"id":94,"name":"Merill","car":"Pontiac","city":"Tsagaan-Owoo"},
{"id":95,"name":"Dru","car":"Mazda","city":"Citambal"},
{"id":96,"name":"Darrell","car":"Mercedes-Benz","city":"Diapaga"},
{"id":97,"name":"Helen-elizabeth","car":"Chrysler","city":"Mikulčice"},
{"id":98,"name":"Charyl","car":"Buick","city":"Torre"},
{"id":99,"name":"Ferrel","car":"Austin","city":"Pingtang"},
{"id":100,"name":"Ronni","car":"BMW","city":"Paipa"},
{"id":101,"name":"Forrest","car":"GMC","city":"Prroshyan"},
{"id":102,"name":"Rodie","car":"GMC","city":"Binagadi"},
{"id":103,"name":"Philippa","car":"Land Rover","city":"Gesing"},
{"id":104,"name":"Waiter","car":"Dodge","city":"Mondorf-les-Bains"},
{"id":105,"name":"Rachelle","car":"Cadillac","city":"Sokarame"},
{"id":106,"name":"Kimberley","car":"Volkswagen","city":"Chakari"},
{"id":107,"name":"Lynett","car":"Volvo","city":"Sungaimaja"},
{"id":108,"name":"Flinn","car":"Chevrolet","city":"Leiguan"},
{"id":109,"name":"Willamina","car":"Infiniti","city":"Jinjiahe"},
{"id":110,"name":"Hatty","car":"Nissan","city":"Manhan"},
{"id":111,"name":"Bunni","car":"MINI","city":"Maluno Sur"},
{"id":112,"name":"Joceline","car":"BMW","city":"Sịa"},
{"id":113,"name":"Moyna","car":"Toyota","city":"Kaca"},
{"id":114,"name":"Pate","car":"Bentley","city":"Trenton"},
{"id":115,"name":"Padraig","car":"Isuzu","city":"Oslo"},
{"id":116,"name":"Rhea","car":"Maserati","city":"Krzczonów"},
{"id":117,"name":"Mitchel","car":"GMC","city":"Sam Ngam"},
{"id":118,"name":"Horst","car":"Mitsubishi","city":"Kamwenge"},
{"id":119,"name":"Madelin","car":"Ford","city":"Kamionka Wielka"},
{"id":120,"name":"Reina","car":"GMC","city":"Gornje Moštre"},
{"id":121,"name":"Alyss","car":"Volkswagen","city":"Uspenskoye"},
{"id":122,"name":"Seward","car":"Cadillac","city":"Jumpangdua"},
{"id":123,"name":"Karlens","car":"Lamborghini","city":"San Francisco"},
{"id":124,"name":"Pier","car":"Mitsubishi","city":"Rimus"},
{"id":125,"name":"Jennine","car":"Ford","city":"Xiaomenjia"},
{"id":126,"name":"Felipa","car":"Audi","city":"Hougaoshizhuang"},
{"id":127,"name":"Winthrop","car":"Ford","city":"Kananga"},
{"id":128,"name":"Ximenes","car":"Oldsmobile","city":"Paris 12"},
{"id":129,"name":"Courtnay","car":"Isuzu","city":"Al Ya‘rubīyah"},
{"id":130,"name":"Gilda","car":"BMW","city":"Perovo"},
{"id":131,"name":"Rhonda","car":"Mitsubishi","city":"Sutton"},
{"id":132,"name":"Dodi","car":"Nissan","city":"Hammarö"},
{"id":133,"name":"Cherri","car":"Oldsmobile","city":"Otradnoye"},
{"id":134,"name":"Herbert","car":"Hyundai","city":"Santiago"},
{"id":135,"name":"Wallache","car":"Plymouth","city":"Kyaiklat"},
{"id":136,"name":"Linette","car":"Hyundai","city":"Karangparwa"},
{"id":137,"name":"Mathe","car":"Chevrolet","city":"Gafanha da Encarnação"},
{"id":138,"name":"Osborn","car":"Toyota","city":"Cerrillos"},
{"id":139,"name":"Kiel","car":"Smart","city":"Sabana de Parra"},
{"id":140,"name":"Towney","car":"Toyota","city":"Puconci"},
{"id":141,"name":"Eveleen","car":"Toyota","city":"Předklášteří"},
{"id":142,"name":"Juana","car":"Pontiac","city":"Yeshan"},
{"id":143,"name":"Gussie","car":"Mazda","city":"Pilar"},
{"id":144,"name":"Iggy","car":"Chevrolet","city":"Nazaré"},
{"id":145,"name":"Elene","car":"Nissan","city":"Eshan"},
{"id":146,"name":"Loise","car":"Chevrolet","city":"Tilcara"},
{"id":147,"name":"Rey","car":"Infiniti","city":"Yunlong"},
{"id":148,"name":"Basilius","car":"Hyundai","city":"Čáslav"},
{"id":149,"name":"Zebadiah","car":"Mazda","city":"Al Karāmah"},
{"id":150,"name":"Marla","car":"Chevrolet","city":"Samacá"},
{"id":151,"name":"Morrie","car":"Toyota","city":"Kradinan"},
{"id":152,"name":"Kimball","car":"Mercury","city":"Thawi Watthana"},
{"id":153,"name":"Forrest","car":"Audi","city":"Xinhua"},
{"id":154,"name":"Gerald","car":"GMC","city":"Tampakan"},
{"id":155,"name":"Hedwiga","car":"Pontiac","city":"Miaoshou"},
{"id":156,"name":"Domini","car":"Volkswagen","city":"Qingxi"},
{"id":157,"name":"Melonie","car":"Acura","city":"Fleury-les-Aubrais"},
{"id":158,"name":"Reynolds","car":"Mercedes-Benz","city":"Nakhon Pathom"},
{"id":159,"name":"Bordy","car":"Cadillac","city":"Kirove"},
{"id":160,"name":"Bern","car":"Chevrolet","city":"Ropa"},
{"id":161,"name":"Nata","car":"Saab","city":"Acobamba"},
{"id":162,"name":"Antonin","car":"Volkswagen","city":"Amouguer"},
{"id":163,"name":"Angie","car":"Chevrolet","city":"Chirpan"},
{"id":164,"name":"Letti","car":"Lamborghini","city":"Zapala"},
{"id":165,"name":"Mariya","car":"Land Rover","city":"Rathnew"},
{"id":166,"name":"Ronica","car":"Chevrolet","city":"Ystad"},
{"id":167,"name":"Gina","car":"Ford","city":"Kościelec"},
{"id":168,"name":"Jill","car":"Ford","city":"Gayamdesa"},
{"id":169,"name":"Anallese","car":"Saab","city":"Carrefour"},
{"id":170,"name":"Luce","car":"Acura","city":"Warungtanjung"},
{"id":171,"name":"Horatius","car":"Pontiac","city":"Tetebatu"},
{"id":172,"name":"Alaric","car":"Mercedes-Benz","city":"Gelgaudiškis"},
{"id":173,"name":"Veradis","car":"Suzuki","city":"Vale de Figueira"},
{"id":174,"name":"Dur","car":"Dodge","city":"Borgo Maggiore"},
{"id":175,"name":"Isa","car":"Mercedes-Benz","city":"Borisovka"},
{"id":176,"name":"Eugene","car":"Dodge","city":"Drosáto"},
{"id":177,"name":"Shurlock","car":"Hummer","city":"Casais Brancos"},
{"id":178,"name":"Waly","car":"Volvo","city":"Candelaria"},
{"id":179,"name":"Carmella","car":"Volkswagen","city":"Altamira"},
{"id":180,"name":"Agretha","car":"Volkswagen","city":"Rožmitál pod Třemšínem"},
{"id":181,"name":"Tatum","car":"Volvo","city":"Herrera"},
{"id":182,"name":"Weidar","car":"Audi","city":"Magoúla"},
{"id":183,"name":"Madelina","car":"Ford","city":"Konārak"},
{"id":184,"name":"Madlin","car":"Aston Martin","city":"Santiago Puringla"},
{"id":185,"name":"Natalie","car":"Ford","city":"Saryg-Sep"},
{"id":186,"name":"Holli","car":"Mercedes-Benz","city":"Pilaya"},
{"id":187,"name":"Neala","car":"BMW","city":"Dordrecht"},
{"id":188,"name":"Kahaleel","car":"Mercury","city":"Sagaing"},
{"id":189,"name":"Violetta","car":"Toyota","city":"Nezvěstice"},
{"id":190,"name":"Travers","car":"Rolls-Royce","city":"Pamatang"},
{"id":191,"name":"Jarrid","car":"GMC","city":"Moss"},
{"id":192,"name":"Thane","car":"Subaru","city":"Saint-Quentin"},
{"id":193,"name":"Durand","car":"Saab","city":"Orléans"},
{"id":194,"name":"Thebault","car":"Suzuki","city":"Yokosuka"},
{"id":195,"name":"Dylan","car":"GMC","city":"Anbyŏn-ŭp"},
{"id":196,"name":"Kim","car":"Plymouth","city":"Koutsopódi"},
{"id":197,"name":"Madelene","car":"Nissan","city":"Kafr Mandā"},
{"id":198,"name":"Murial","car":"Acura","city":"Erhe"},
{"id":199,"name":"Stephanie","car":"Cadillac","city":"Lagoa"},
{"id":200,"name":"Bradly","car":"Buick","city":"Bar-le-Duc"}]



for(user of users){
    if(user.car ==="Nissan"){
            console.log(user.name, user.car)
    }
}